In [12]:
import numpy as np 
import pandas as pd

# Load dataset

In [13]:
df=pd.read_csv(r"Countries.csv" )# loading the dataset into a pandas data frame
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

# Preprocess

In [14]:
df.shape

(194, 64)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    str
 1   country_long                             194 non-null    str
 2   currency                                 194 non-null    str
 3   capital_city                             194 non-null    str
 4   region                                   194 non-null    str
 5   continent                                194 non-null    str
 6   demonym                                  194 non-null    str
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    str
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    str
 63  title                                    187 non-null    str
dtypes: float64(48), int64(6), str(10)
memory usage: 119.7 KB

In [16]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

# which country has the highest population

In [17]:
df[df['population'] == df['population'].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [18]:
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: str

In [19]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='str')

# What is the capital of the country with highest population

In [ ]:
df[df['population'] == df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: str

# which country has the least population

In [22]:
df[df['population'] == df['population'].min()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.0,178.0,18.0,...,11312,6.25,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister

In [20]:
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: str

# what is the capital of the country with least population

In [23]:
df[df['population'] == df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: str

# give me top 5 countries with highest democratic score

In [27]:
df.sort_values(by = 'democracy_score',ascending=False,inplace = True)
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [ ]:
df['country'].head() # or df.head()['country']

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [28]:
df.head()['country']

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: str

# how many total regions are there

In [33]:
#counting the number of unique regions in the dataset
df['region'].value_counts()

region
Eastern Africa               17
Western Asia                 17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Northern Europe              10
Eastern Europe               10
Middle Africa                10
Western Europe                9
Southern Asia                 9
Central America               8
Northern Africa               6
Eastern Asia                  5
Southern Africa               5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [34]:
#counting the number of unique regions in the dataset
df['region'].value_counts().count()
print(f"There are {df['region'].value_counts().count()} regions in the dataset.")

There are 22 regions in the dataset.

# how many countries lie in Eastern Europe region

In [ ]:
#how many countries lie in Eastern Europe region it give whole data or row of Eastern Europe region
df[df['region']=='Eastern Europe']

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.5,35238.7,...,10526073,25.5000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.5,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.0,50470.0,...,6465097,24.1667,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister
136,Poland,Republic of Poland,Polish zloty,Warsaw,Eastern Europe,Europe,Polish,52.000000,20.0,144610.0,...,37561599,28.2609,14974307,22587292,2.71,6.67,Flawed democracy,36.3,Mateusz Morawiecki,Prime Minister
73,Hungary,Hungary,Hungarian forint,Budapest,Eastern Europe,Europe,Hungarian,47.000000,20.0,49030.0,...,9683505,14.0704,2657928,7025577,2.57,6.63,Flawed democracy,38.1,Viktor Orbán,Prime Minister
139,Romania,Romania,New Romanian leu,Bucharest,Eastern Europe,Europe,Romanian,46.000000,25.0,135910.0,...,18956666,19.0909,8627368,10329298,3.05,6.38,Flawed democracy,37.4,Klaus Iohannis,President
111,Moldova,Republic of Moldova,Moldovan leu,Chișinău,Eastern Europe,Europe,Moldovan,47.000000,29.0,22646.0,...,2592477,40.5941,1473227,1119250,2.51,5.85,Hybrid regime,31.2,Ion Chicu,Prime Minister
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.0,413110.0,...,38000000,20.3310,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.0,82810.0,...,9208701,40.0000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.000000,100.0,2154940.0,...,143555736,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President

In [40]:
#eastern europe region ki row ki saree column ki counting kar lega
df[df['region'] == "Eastern Europe"].count()

country             10
country_long        10
currency            10
capital_city        10
region              10
                    ..
democracy_score     10
democracy_type      10
median_age          10
political_leader     9
title                9
Length: 64, dtype: int64

In [41]:
#only country column ki counting kar lega
df[df['region'] == "Eastern Europe"][['country']].count()

country    10
dtype: int64

In [43]:
df['region'].value_counts()['Eastern Europe']

np.int64(10)

# who is the political leader of the 2nd highest populated country

In [48]:
# Get the series of n rows with the largest population
df['population'].nlargest(5) # it will give series with own labels but  we are accessing the index of the series to get the ith largest population

75     1417173173
34     1412175000
184     333287557
76      275501339
129     235824862
Name: population, dtype: int64

In [ ]:
df['population'].nlargest(2).iloc[1] #it give the 2nd largest population

np.int64(1412175000)

In [ ]:
df['population'] == df['population'].nlargest(2).iloc[1] # it give the boolean series where the 2nd largest population is present

127    False
74     False
164    False
122    False
46     False
       ...
156    False
174    False
170    False
179    False
187    False
Name: population, Length: 194, dtype: bool

In [ ]:
df[df['population'] == df['population'].nlargest(2).iloc[1]]  # where the boolean series is true it will give that rows,

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party

In [ ]:
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader'] #then we are accessing the political_leader column of that row

34    Xi Jinping
Name: political_leader, dtype: object

# how many countries are there whoes political leaders are unknown

In [50]:
df['political_leader'].isna() #returns a boolean series where the value is True if the political_leader column is NaN (missing) and False otherwise.

127    False
74     False
164    False
122    False
46     False
       ...
156    False
174    False
170    False
179    False
187    False
Name: political_leader, Length: 194, dtype: bool

In [51]:
df[df['political_leader'].isna()] #it will give the rows where the political_leader column is NaN (missing)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.8889,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
172,Timor-Leste,Democratic Republic of Timor-Leste,U.S. dollar,Dili,South-Eastern Asia,Asia,East Timorese,-8.833333,125.916667,3414.0,...,1341296,40.0000,911089,430207,2.61,7.19,Flawed democracy,16.7,NaN,NaN
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.500000,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
161,St. Vincent and the Grenadines,St. Vincent and the Grenadines,East Caribbean dollar,Kingstown,Caribbean,Americas,Saint Vincentian,13.250000,-61.200000,70.0,...,103948,18.1818,47946,56002,0.00,0.00,Unknown,29.1,NaN,NaN
159,St. Kitts and Nevis,St. Kitts and Nevis,East Caribbean dollar,Basseterre,Caribbean,Americas,Kittian and Nevisian,17.333333,-62.750000,60.0,...,47657,31.2500,32888,14769,0.00,0.00,Unknown,30.4,NaN,NaN
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.4,...,179857,11.1111,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN

In [53]:
df[df['political_leader'].isna()]['country'].count() # it will give the count of rows where the political_leader column is NaN (missing) bcz .count() give count for all col of dataset but we are accessing the country column to get the count of that column only

np.int64(7)

# how many country have Republic in their full name

In [54]:
df.head(2)['country_long']

127      Kingdom of Norway
74     Republic of Iceland
Name: country_long, dtype: str

In [67]:
# fun that counts the number of times the word 'republic' appears in the 'country_long' column
count = 0
def counting(txt):
    global count  # since count variable is not accessible outside the function so we need to declare it as global variable so that it can be accessed outside the function.
    if 'republic' in txt.lower():
        count+= 1
    return txt

In [68]:
# This will apply the counting function to each value in the 'country_long' column and update the column with the returned values
# note this will not change the original 'country_long' column, it will just apply the function and return the modified values. 
# we when we run this code it also print text for each row of country_long column and also count the number of times the word 'republic' appears in the 'country_long' column
#so we need not to print the text for each row of country_long column so we assigned the returned values to the same column 'country_long' so that it will not print the text for each row of country_long column. 
df['country_long'] = df['country_long'].apply(counting)

In [69]:
# but count vb works well after the apply function is executed because the apply function will call the counting function for each row of the 'country_long' column and update the count variable accordingly.

# so we can print the count variable after the apply function is executed to get the number of times the word 'republic' appears in the 'country_long' column.
print(count)

125

# which country in african region has highest population

In [71]:
africa_df = df[df['continent'] == 'Africa'] # it returns a new DataFrame containing only the rows where the 'continent' column is equal to 'Africa'. This is useful for analyzing data specific to African countries.
africa_df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.55,860.0,...,1262523,20.0000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.00,790.0,...,593149,38.8889,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.00,258620.0,...,2630296,11.1111,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.00,963410.0,...,59893885,46.5000,18965399,40928486,3.52,7.24,Flawed democracy,23.3,Cyril Ramaphosa,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.50,26000.0,...,2305825,26.4463,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister

In [72]:
africa_df[africa_df['population'] == africa_df['population'].max()] # it will give the row of the African country with the largest population.

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.0,8.0,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President

In [73]:
africa_df[africa_df['population'] == africa_df['population'].max()]['country'] #it will give the country name of the African country with the largest population.

125    Nigeria
Name: country, dtype: str