In [39]:
import numpy as np 
import pandas as pd

**Creating a DataFrame**

In [40]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
data_list = [
    ['John', 28, 'New York', 65000], #but header ke name nhi aaye
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df_2 = pd.DataFrame(data_list)
df_2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [42]:

columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns) #manaulaay column set for list
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
print(df["Name"]) #only one column
print(df["City"])

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object
0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [45]:
df2[["Name","City"]] # more than one column together

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new column**

In [46]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."] #new column add krna
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Removing Columns**

In [47]:
df2.drop("Designation",axis = 1) #main se delete nhi krta only deleted ke saath snapshot de deta hai

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
df2 #note delete nhi hua hai

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [49]:
df2.drop("Designation",axis = 1,inplace=True) #main se delete krne ke liye
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
df2.drop(["Name","Age"],axis = 1,inplace=True) #main se  multiple delete krne ke liye
df2

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000
3    London   85000

In [61]:
df2 = pd.DataFrame(data_list,columns =columns) #again create
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [64]:
df2.drop(0,axis = 0)  #row delete note inplace nhi kiya but kr skte hai

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [65]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting Rows**

In [67]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[0] #only single row

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [70]:
df2.loc[[0,1]] #multiple row

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [71]:
df.iloc[3] # or u can use index

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [72]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [79]:
df.loc[[1,3]][["Age","City"]] #note jo likho whi its not range

   Age    City
1   34   Paris
3   42  London

In [80]:
df.loc[[2,1]][["Age","Salary"]]

   Age  Salary
2   29   62000
1   34   70000

**Conditional Selection**

In [81]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#I only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [85]:
#I only want poeple whose age is above 30 and their city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000