In [1]:
import numpy as np 
import pandas as pd

**Pivot Tables**

In [4]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    245     89   John
1  2023-01-02       B   West    356     87   Mary
2  2023-01-03       C  North    794     75    Bob
3  2023-01-04       D  South    988     45  Alice
4  2023-01-05       A   East    192     58   John
5  2023-01-06       B   West    499     66   Mary
6  2023-01-07       C  North    372     39    Bob
7  2023-01-08       D  South    733     75  Alice
8  2023-01-09       A   East    614     58   John
9  2023-01-10       B   West    248     51   Mary
10 2023-01-11       C  North    153     49    Bob
11 2023-01-12       D  South    977     61  Alice
12 2023-01-13       A   East    437     57   John
13 2023-01-14       B   West    929     20   Mary
14 2023-01-15       C  North    851     82    Bob
15 2023-01-16       D  South    488     98  Alice
16 2023-01-17       A   East    302     95   John
17 2023-01-18       B   West    823     56   Mary
18 2023-01-19       C  North    474     61    Bob
19 2023-01-20       D  South    741     98  Alice

In [5]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    245     89   John  January      Q1
1  2023-01-02       B   West    356     87   Mary  January      Q1
2  2023-01-03       C  North    794     75    Bob  January      Q1
3  2023-01-04       D  South    988     45  Alice  January      Q1
4  2023-01-05       A   East    192     58   John  January      Q1
5  2023-01-06       B   West    499     66   Mary  January      Q1
6  2023-01-07       C  North    372     39    Bob  January      Q1
7  2023-01-08       D  South    733     75  Alice  January      Q1
8  2023-01-09       A   East    614     58   John  January      Q1
9  2023-01-10       B   West    248     51   Mary  January      Q1
10 2023-01-11       C  North    153     49    Bob  January      Q1
11 2023-01-12       D  South    977     61  Alice  January      Q1
12 2023-01-13       A   East    437     57   John  January      Q1
13 2023-01-14       B   West    929     20   Mary  January      Q1
14 2023-01-15       C  North    851     82    Bob  January      Q1
15 2023-01-16       D  South    488     98  Alice  January      Q1
16 2023-01-17       A   East    302     95   John  January      Q1
17 2023-01-18       B   West    823     56   Mary  January      Q1
18 2023-01-19       C  North    474     61    Bob  January      Q1
19 2023-01-20       D  South    741     98  Alice  January      Q1

In [ ]:
#what is a pivot table? it is a data summarization tool that is used in data processing. Pivot tables are used to summarize, sort, reorganize, group, count, total or average data stored in a database. It allows its users to transform columns into rows and rows into columns. It allows grouping by any data field (column). It allows us to create a new derived table out of the original table.

pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product") #creates a pivot table with Region as rows and Product as columns bydefault the aggregation function is mean but we can change it to sum or any other function using aggfunc parameter

Product      A      B      C      D
Region
East     358.0    NaN    NaN    NaN
North      NaN    NaN  528.8    NaN
South      NaN    NaN    NaN  785.4
West       NaN  571.0    NaN    NaN

In [ ]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median') # pivot in which the aggregation function is median instead of mean also in which index is Region and columns is Product and sales is the value to be aggregated

Product      A      B      C      D
Region
East     302.0    NaN    NaN    NaN
North      NaN    NaN  474.0    NaN
South      NaN    NaN    NaN  741.0
West       NaN  499.0    NaN    NaN

In [12]:
#jitne vales ko aggregate karna hai unko values me pass karenge aur jitne columns aur rows chahiye unko index aur columns me pass karenge.
#jitnes value doge unke liye alag alag pivot table banega.
#and for aggregate in values use only numeric data
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product') #it creates a pivot table with Region as rows and Product as columns for both values separately. Sales and Units as values to be aggregated by default the aggregation function is mean but we can change it to sum or any other function using aggfunc parameter
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     358.0    NaN    NaN    NaN  71.4   NaN   NaN   NaN
North      NaN    NaN  528.8    NaN   NaN   NaN  61.2   NaN
South      NaN    NaN    NaN  785.4   NaN   NaN   NaN  75.4
West       NaN  571.0    NaN    NaN   NaN  56.0   NaN   NaN

**Cross Tabs**

In [ ]:
pd.crosstab(df['Region'],df['Product']) #work as above but crosstab is used for count data while pivot table is used for aggregate data. It creates a cross tabulation table that shows the frequency distribution of the variables. It is used to compute a simple cross-tabulation of two (or more) factors. By default, it computes a frequency table of the factors unless an array of values and an aggregation function are passed.

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0