In [1]:
import numpy as np 
import pandas as pd

**DataFrames Basic Operations**

In [3]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df1.shape #gives the number of rows and columns in the dataframe

(5, 3)

In [5]:
df1.columns # gives the column names of the dataframe

Index(['A', 'B', 'C'], dtype='str')

In [6]:
df1.info() # gives information about the dataframe including the data types and memory usage

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [9]:
df1.describe() # gives a statistical summary of the dataframe based on the numerical columns

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A'] + 10 # adds 10 to each value in column A and returns a new series only with the updated values. The original dataframe remains unchanged.

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames Applying Functions**

In [12]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [14]:
df1['A']**2

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [13]:
def square(x):
    return x**2

df1['A'].apply(square) # applies the square function to each value in column A and returns a new series with the updated values. The original dataframe remains unchanged.

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [16]:
df1['D']=df1['A'].apply(square) #add new column D to the dataframe with the squared values of column A
df1

   A   B    C   D
0  1  10  100   1
1  2  20  200   4
2  3  30  300   9
3  4  40  400  16
4  5  50  500  25

In [18]:
df1['E'] = df1["B"].apply(lambda x : x**2) #with lambda function we can apply a function to each value in column B and return a new series with the updated values. The original dataframe remains unchanged.

In [19]:
df1

   A   B    C   D     E
0  1  10  100   1   100
1  2  20  200   4   400
2  3  30  300   9   900
3  4  40  400  16  1600
4  5  50  500  25  2500

**we learn apply in depth for real data feature extraction**